name: myaquaponic
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"



# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
    

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^9.0.0
  # firebase_auth: ^3.0.1
  # firebase_core: ^1.4.0
  firebase_core: ^1.0.4
  firebase_auth: ^1.1.1
  google_sign_in: ^5.2.0
  provider: ^4.0.4
  modal_progress_hud: ^0.1.3
  curved_navigation_bar: ^1.0.3
  firebase_database: ^6.0.0
  firebase_storage: ^10.2.0
  cloud_firestore: ^3.1.9
  cloud_firestore_web: ^2.6.9
  image_picker: ^0.8.5
  fl_chart: ^0.55.0
  intl: ^0.17.0
  charts_flutter: ^0.11.0
  getwidget: 2.0.4
  ff_navigation_bar: ^0.1.5
  fancy_bottom_navigation: ^0.3.3
  bottom_navy_bar: ^6.0.0
  syncfusion_flutter_gauges: ^18.2.44
  percent_indicator: ^4.0.0
  syncfusion_flutter_charts: ^18.4.48
  email_auth: ^1.0.0
  # firebase_analytics: ^9.1.0
  get: ^4.3.8
  cached_network_image: ^2.5.0
  material_color_utilities: ^0.1.3
  # gallery_saver: ^2.3.2
  # firebase_messaging_platform_interface: 3.1.6
  # transparent_image: ^1.0.0
  # material_color_utilities: ^0.1.4
 


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^0.2.8
  form_field_validator: ^1.1.0
  
  
flutter_native_splash:
  color: "#ffffff"
  image: images/splashscreen.png
  android: true
  ios: true
  android_gravity: fill
  ios_content_mode: scaleAspectFill    

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

 
  assets:
    - images/login.png
    - images/google.png
    - images/tangan.png
    - images/ph.png
    - images/suhu.png
    - images/suhu2.png
    - images/tanaman.png
    - images/ikan.png
    - images/air.png
    - images/akuaponik.png
    - images/splashscreen.png
    - images/googlee.png
    - images/logo.png
    - images/parametersuhu.png
    - images/grafiksuhu.png
    - images/ph2.png
    - images/air2.png
    - images/kangkung.png
    - images/pakan.png
    - images/hello.png
    - images/password.png
    - images/forgotpass.png
    - images/arrow.png
  
  
    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
